// flow-typed signature: c15d14d7b68dfb7d0ae82451a2f06492
// flow-typed version: <<STUB>>/apollo_v^2.18.0/flow_v0.102.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'apollo'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'apollo' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'apollo/lib/Command' {
  declare module.exports: any;
}

declare module 'apollo/lib/commands/client/check' {
  declare module.exports: any;
}

declare module 'apollo/lib/commands/client/codegen' {
  declare module.exports: any;
}

declare module 'apollo/lib/commands/client/download-schema' {
  declare module.exports: any;
}

declare module 'apollo/lib/commands/client/extract' {
  declare module.exports: any;
}

declare module 'apollo/lib/commands/client/push' {
  declare module.exports: any;
}

declare module 'apollo/lib/commands/service/check' {
  declare module.exports: any;
}

declare module 'apollo/lib/commands/service/delete' {
  declare module.exports: any;
}

declare module 'apollo/lib/commands/service/download' {
  declare module.exports: any;
}

declare module 'apollo/lib/commands/service/list' {
  declare module.exports: any;
}

declare module 'apollo/lib/commands/service/push' {
  declare module.exports: any;
}

declare module 'apollo/lib/defaultValidationRules' {
  declare module.exports: any;
}

declare module 'apollo/lib/generate' {
  declare module.exports: any;
}

declare module 'apollo/lib/git' {
  declare module.exports: any;
}

declare module 'apollo/lib/index' {
  declare module.exports: any;
}

declare module 'apollo/lib/OclifLoadingHandler' {
  declare module.exports: any;
}

declare module 'apollo/lib/utils/getOperationManifestFromProject' {
  declare module.exports: any;
}

declare module 'apollo/lib/utils/index' {
  declare module.exports: any;
}

declare module 'apollo/lib/utils/pluralize' {
  declare module.exports: any;
}

declare module 'apollo/lib/utils/validateHistoricParams' {
  declare module.exports: any;
}

// Filename aliases
declare module 'apollo/lib/Command.js' {
  declare module.exports: $Exports<'apollo/lib/Command'>;
}
declare module 'apollo/lib/commands/client/check.js' {
  declare module.exports: $Exports<'apollo/lib/commands/client/check'>;
}
declare module 'apollo/lib/commands/client/codegen.js' {
  declare module.exports: $Exports<'apollo/lib/commands/client/codegen'>;
}
declare module 'apollo/lib/commands/client/download-schema.js' {
  declare module.exports: $Exports<'apollo/lib/commands/client/download-schema'>;
}
declare module 'apollo/lib/commands/client/extract.js' {
  declare module.exports: $Exports<'apollo/lib/commands/client/extract'>;
}
declare module 'apollo/lib/commands/client/push.js' {
  declare module.exports: $Exports<'apollo/lib/commands/client/push'>;
}
declare module 'apollo/lib/commands/service/check.js' {
  declare module.exports: $Exports<'apollo/lib/commands/service/check'>;
}
declare module 'apollo/lib/commands/service/delete.js' {
  declare module.exports: $Exports<'apollo/lib/commands/service/delete'>;
}
declare module 'apollo/lib/commands/service/download.js' {
  declare module.exports: $Exports<'apollo/lib/commands/service/download'>;
}
declare module 'apollo/lib/commands/service/list.js' {
  declare module.exports: $Exports<'apollo/lib/commands/service/list'>;
}
declare module 'apollo/lib/commands/service/push.js' {
  declare module.exports: $Exports<'apollo/lib/commands/service/push'>;
}
declare module 'apollo/lib/defaultValidationRules.js' {
  declare module.exports: $Exports<'apollo/lib/defaultValidationRules'>;
}
declare module 'apollo/lib/generate.js' {
  declare module.exports: $Exports<'apollo/lib/generate'>;
}
declare module 'apollo/lib/git.js' {
  declare module.exports: $Exports<'apollo/lib/git'>;
}
declare module 'apollo/lib/index.js' {
  declare module.exports: $Exports<'apollo/lib/index'>;
}
declare module 'apollo/lib/OclifLoadingHandler.js' {
  declare module.exports: $Exports<'apollo/lib/OclifLoadingHandler'>;
}
declare module 'apollo/lib/utils/getOperationManifestFromProject.js' {
  declare module.exports: $Exports<'apollo/lib/utils/getOperationManifestFromProject'>;
}
declare module 'apollo/lib/utils/index.js' {
  declare module.exports: $Exports<'apollo/lib/utils/index'>;
}
declare module 'apollo/lib/utils/pluralize.js' {
  declare module.exports: $Exports<'apollo/lib/utils/pluralize'>;
}
declare module 'apollo/lib/utils/validateHistoricParams.js' {
  declare module.exports: $Exports<'apollo/lib/utils/validateHistoricParams'>;
}
