// flow-typed signature: 4bd869a255989679ec9a052398e72fbc
// flow-typed version: <<STUB>>/react-apollo_v^3.0.1/flow_v0.102.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-apollo'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-apollo' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'react-apollo/lib/index' {
  declare module.exports: any;
}

declare module 'react-apollo/lib/react-apollo.cjs' {
  declare module.exports: any;
}

declare module 'react-apollo/lib/react-apollo.cjs.min' {
  declare module.exports: any;
}

declare module 'react-apollo/lib/react-apollo.esm' {
  declare module.exports: any;
}

declare module 'react-apollo/lib/react-apollo.umd' {
  declare module.exports: any;
}

// Filename aliases
declare module 'react-apollo/lib/index.js' {
  declare module.exports: $Exports<'react-apollo/lib/index'>;
}
declare module 'react-apollo/lib/react-apollo.cjs.js' {
  declare module.exports: $Exports<'react-apollo/lib/react-apollo.cjs'>;
}
declare module 'react-apollo/lib/react-apollo.cjs.min.js' {
  declare module.exports: $Exports<'react-apollo/lib/react-apollo.cjs.min'>;
}
declare module 'react-apollo/lib/react-apollo.esm.js' {
  declare module.exports: $Exports<'react-apollo/lib/react-apollo.esm'>;
}
declare module 'react-apollo/lib/react-apollo.umd.js' {
  declare module.exports: $Exports<'react-apollo/lib/react-apollo.umd'>;
}
